version: '3.7'

services:
  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: admin1234
      MYSQL_DATABASE: tSeriesDB
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
    ports:
      - "6033:3306"
    volumes:
      - dbdata:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
  node-red:
    image: nodered/node-red:latest
    ports:
      - "1880:1880"
  mosquitto:
    image: eclipse-mosquitto:1.6
    ports:
      - "9001:9001"
      - "1883:1883"
volumes:
  dbdata: